server:
  port: 9010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/razorpay-merchant-db

jwt:
  secret-key: c3VwZXItc2VjcmV0LWtleS1mb3ItcmF6b3JwYXktdmF1bHQtc2VydmljZS0yNTYtYml0cw==

webhook:
  secret-encryption-key: sGjTBSamOvV1MGxObP9s5XXaaoTWGUIe092ZCvmVlV4=

---

spring:
  config:
    activate:
      on-profile: k8s
  datasource:
    url: jdbc:postgresql://postgres.razorpay-core.svc.cluster.local:5432/razorpay-merchant-db
    username: merchant_user
    password: ${MERCHANT_DB_PASSWORD}

jwt:
  secret-key: ${JWT_SECRET}

webhook:
  secret-encryption-key: ${WEBHOOK_SECRET_ENCRYPTION_KEY}
